spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

  flyway:
    enabled: true

  thymeleaf:
    cache: false
    
  web:
    resources:
      cache:
        period: 0

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: INFO
